#!/bin/sh

## Assert the IDE hasn't inserted any spurious package imports for local files.
pkg="nitpicky"

grep -r "package:$pkg" lib/
res=$?

if [ $res -ne 1 ]; then
  cat<<-EOF
  ERROR: A file in lib/ references this package with a 'package:' import.
  Use relative imports instead.
EOF
  exit 11
fi

exit 0
